#!/bin/sh

geth --datadir=/ethereum/data --ethash.dagdir=/ethereum/ethash init /ethereum/genesis.json
#mkdir -p /ethereum/ethash && geth --datadir /ethereum/data makedag 0 /ethereum/ethash

exec "$@"
